package genspark.projects.project1;

import java.util.ArrayList;
import java.util.Random;

public class NumberGuesser {

    // class which talks to the user
    protected UserIn player;
    // highest guessable number
    protected int maxNumber = 20;
    // list of guesses from the user
    protected ArrayList<Integer> guesses = new ArrayList<>(maxNumber);
    // random number generated by this program
    private int randNum;

    // This is the constructor that the index will call
    NumberGuesser() {
        startGame();
        userGuess();
        player.replay();
    }

    // this constructor means the player is replaying
    NumberGuesser(String name) {
        restartGame(name);
        userGuess();
        player.replay();
    }
    
    // this constructor means the same user is playing, and they want to change the
    // max number
    NumberGuesser(String name, int num) {
        this.maxNumber = num;
        restartGame(name);
        userGuess();
        player.replay();
    }

    private void startGame() {
        player = new UserIn();
        player.setIn(System.in);
        player.setName();
        challenge();
    }
    
    private void restartGame(String name) {
        player = new UserIn(name);
        player.setIn(System.in);
        System.out.println("Okay " + player.getName() + ", Here we go again!\n");
        challenge();
    }

    private void challenge() {
        String challenge = """
                Hey %name, Guess the secret number.
                It's between 0 and %max.
                """;
        challenge = challenge.replace("%max", maxNumber + "");
        challenge = challenge.replace("%name", player.getName());
        System.out.println(challenge);
    }

    private void setRandomNumber(int max) {
        final Random rand = new Random();
        randNum = rand.nextInt(max + 1);
    }

    private void userGuess() {
        int count = 0;
        int guess;
       
        setRandomNumber(maxNumber);
        
        do {
            guess = player.getNumber();
            guesses.add(guess);
            ++count;
            // number is correct
            if (guess == randNum) {
                correctAnswer(count);
                break;
            }
            // number is in the negatives
            if (guess < 0) {
                wayTooLow();
            }
            // number is greater than max
            else if (guess > maxNumber) {
                wayTooHigh();
            }
            // higher than random
            else if (guess > randNum) {
                System.out.println("That number is too high.");
            }
            // lower than random
            else if (guess < randNum) {
                System.out.println("That number is too low.");
            }
            printGuesses();
        } while (guess != randNum);
        System.out.println("Here are the numbers you tried : " + guesses.toString());
        System.out.println();
    }

    private void printGuesses() {
        String guessed = guesses.toString();
        String numbers = """
                Numbers guessed so far : %numbers
                """;
        numbers = numbers.replace("%numbers", guessed.substring(1, guessed.length() - 1));
        System.out.println(numbers);

    }

    private void correctAnswer(int numTimes) {
        String genius = """
                That's exactly it, %name.
                You figured it out in %int attempts.""";
        genius = genius.replace("%int", numTimes + "");
        genius = genius.replace("%name", player.getName());
        System.out.println(genius);
    }

    private void wayTooHigh() {
        String str = """
                That number's way too high, %name.
                I told you the number is less than %max.""";
        str = str.replace("%max", maxNumber + "");
        str = str.replace("%name", player.getName());
        System.out.println(str);
    }

    private void wayTooLow() {
        String str = """
                I told you it's not a negative, %name.
                The number is greater than 0.""";
        str = str.replace("%name", player.getName());
        System.out.println(str);
    }
}
